#!/usr/bin/env python3
"""
test_state_facts.py — lock in the invariants of cvrf_parse's classification logic
(population separation, product category, finder bucket, severity/reboot-class aggregation).

*Runs on synthetic data*
    Real MSRC primary data (which contains researchers' personal information) is not bundled,
    so this uses the synthetic CVRF generated by tests/fixtures/make_synthetic_cvrf.py.
    The exact counts come from the synthetic data, but what is verified is the structural
    invariants the classification logic must satisfy (population conservation, bucket
    exclusivity, category internal-keying, etc.).

Run:
    python tests/fixtures/make_synthetic_cvrf.py   # generate the synthetic fixture
    python tests/test_state_facts.py
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import cvrf_parse as cp

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures",
                       "2026-Jul-cvrf-reduced.json")
FINDER_BUCKETS = {"external", "ms_internal", "uncredited", "anonymous", "hash_anon"}
KEY_RE = re.compile(r"^[a-z0-9_]+$")


def _summ():
    doc = json.load(open(FIXTURE, encoding="utf-8"))
    return cp.summarize(doc, "2026-Jul", "synthetic")


# --- totals and population separation: core + excluded == total (conservation) ---
def test_totals_and_population():
    s = _summ()
    assert s["cve_total"] == 50, s["cve_total"]           # scale of the synthetic fixture
    assert s["core_total"] + s["excluded_total"] == s["cve_total"]
    assert s["credited"] + s["uncredited"] == s["cve_total"]
    assert s["excluded_total"] > 0, "the excluded population (Edge/Cloud etc.) is empty"


# --- severity: bucket sum == total -------------------------------------------
def test_severity_sums():
    s = _summ()
    assert sum(s["severity_count"].values()) == s["cve_total"]
    assert sum(s["severity_core"].values()) == s["core_total"]
    assert s["severity_count"].get("Critical", 0) > 0


# --- reboot class: sum == total, and the heavy tier (T2/T3) is countable ------
def test_tier_sums():
    s = _summ()
    t = s["tier_count"]
    assert sum(t.values()) == s["cve_total"]
    assert (t.get("T2", 0) + t.get("T3", 0)) >= 1, "no heavy tier (T2/T3) detected"
    assert sum(s["tier_core"].values()) == s["core_total"]


# --- finder buckets: exclusive and exhaustive (sum == total), bucket names only
#     (no real names baked in) ------------------------------------------------
def test_finder_buckets_partition_and_no_names():
    f = _summ()["finder_bucket"]
    assert sum(f.values()) == 50
    assert set(f) <= FINDER_BUCKETS, f"unknown bucket: {set(f) - FINDER_BUCKETS}"
    # in the synthetic data, external researchers (named credits) are the most common
    assert max(f, key=f.get) == "external", f


# --- Kugelblitz: count CVEs that carry the credit but never surface it in Critical ---
def test_kugelblitz_surface_only():
    s = _summ()
    assert s["kugelblitz"] > 0, "Kugelblitz credits were not aggregated"
    assert s["kugelblitz_in_critical"] == 0, "Kugelblitz leaked into Critical"


# --- Critical breakdown by finder: counts only, no real names; sum matches Critical total ---
def test_critical_by_finder_counts_only():
    s = _summ()
    cbf = s["critical_by_finder"]
    assert sum(cbf.values()) == s["severity_count"]["Critical"], cbf
    assert max(cbf, key=cbf.get) == "external", cbf
    assert cbf["external"] > cbf.get("ms_internal", 0), cbf
    for key in cbf:
        assert key in FINDER_BUCKETS, f"something other than a bucket name (a real name?) leaked in: {key!r}"


# --- product category: internal keys (alphanumeric), Edge is top, "other" is under 12% ---
def test_product_categories_internal_keys():
    s = _summ()
    p = s["product_count"]
    for k in p:
        assert KEY_RE.match(k), f"category key is not an internal key (alphanumeric): {k!r}"
    assert max(p, key=p.get) == "edge_chromium", "Edge is not the top category"
    other = p.get("other", 0)
    assert other / s["cve_total"] < 0.12, f"other {other} exceeds 12%"


# --- runner that also works without pytest ----------------------------------
if __name__ == "__main__":
    import traceback
    tests = [v for k, v in sorted(globals().items())
             if k.startswith("test_") and callable(v)]
    passed = failed = 0
    for t in tests:
        try:
            t()
            print(f"  PASS  {t.__name__}")
            passed += 1
        except AssertionError as e:
            print(f"  FAIL  {t.__name__}: {e}")
            failed += 1
        except Exception:
            print(f"  ERROR {t.__name__}")
            traceback.print_exc()
            failed += 1
    print(f"\n{passed} passed, {failed} failed")
    sys.exit(1 if failed else 0)
